### PR TITLE
Update group11.txt

### PR DESCRIPTION
**Pull request by slurgen**
heya just seeing where this msg pops up
so this is where you discuss pull request

### CODE REVIEW

**Comment by slurgen** [comment]
you need to set push permissions i cant upload files

**Comment by chris771** [comment]
Hey Brodie
Sorry I just saw these messages. Been too busy with assignments etc and didn't look at my emails and didn't see this on github
Will c what I can do to change the permissions so you can upload
Chris
________________________________

**Comment by chris771** [comment]
Hey Brodie
Have added you as a collaborator so you should be able to do whatever you need to. I haven't merged your new file upload so we can see if changing you to a collaborator lets you do it!

**Comment by slurgen** [comment]
i dont know what im doing still cant upload files

**Comment by chris771** [comment]
I dont; know why you can't either. I do know that if you can upload them to your group-test I can pull them into mine.
Are you happy for me to try to upload into yours and see if that works?
________________________________

**Pull request closed without merging**
